import type { TareaHistorialItem } from "./types";

export const mockTareasHistorial: TareaHistorialItem[] = [
  {
    id: 101,
    nombre: "Sanitización de Mesadas y Piletas de Trabajo",
    tipo: "pre-operacional",
    destino: "Sector - Cocina",
    estado: "completada",
    fechaProgramada: "2026-09-24",
    elementosLimpieza: ["2 Paños de microfibra", "1 Pulverizador"],
    procedimiento: [
      "Retirar restos gruesos de materia orgánica con agua tibia.",
      "Aplicar solución sanitizante con pulverizador sobre toda la superficie.",
      "Dejar actuar 10 minutos y repasar con paño limpio.",
    ],
    auditoria: {
      fecha: "2026-09-24",
      hora: "07:15 hs",
      realizadoPor: "Juan Pérez",
      consumoRegistrado: ["100 ml de Lavandina Concentrada"],
      observacion: "Se realizó desinfección profunda sin novedades.",
      fotoNombre: "evidencia_mesada_24.jpg",
      fotoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR17YpPyxqu9Ynbehw0ITphoB0H3h5Ym5IENwQr5ggWvP-gq4h7p9LT5NeX&s=10",
    },
  },
  {
    id: 102,
    nombre: "Limpieza y desinfección de Balanza de Recepción",
    tipo: "pre-operacional",
    destino: "Equipo - Balanza 01 (Recepción)",
    estado: "completada",
    fechaProgramada: "2026-09-24",
    elementosLimpieza: ["4 Papel descartable"],
    procedimiento: [
      "Desconectar o proteger el visor digital.",
      "Desinfectar plato de pesaje con solución alcohólica.",
      "Secar con toalla descartable.",
    ],
    auditoria: {
      fecha: "2026-09-24",
      hora: "07:40 hs",
      realizadoPor: "Juan Pérez",
      consumoRegistrado: ["50 ml de Alcohol 70%"],
      observacion: "Se calibró el platillo luego de desinfectar.",
    },
  },
  {
    id: 103,
    nombre: "Repaso de pisos y drenajes de zona de empaque",
    tipo: "operacional",
    destino: "Sector - Empaque",
    estado: "incumplida",
    fechaProgramada: "2026-09-24",
    elementosLimpieza: ["1 Secador de piso", "1 Cepillo de cerda dura"],
    procedimiento: [
      "Barrer y levantar sólidos hacia el tacho de residuos.",
      "Refregar drenajes con cepillo y agua caliente.",
    ],
    auditoria: {
      fecha: "2026-09-24",
    },
  },
  {
    id: 104,
    nombre: "Sanitización de Heladera Mostrador 1",
    tipo: "pre-operacional",
    destino: "Equipo - Heladera 1 (Cocina)",
    estado: "completada",
    fechaProgramada: "2026-09-23",
    elementosLimpieza: ["1 Esponja suave", "2 Paños descartables"],
    procedimiento: [
      "Vaciar estantes superiores transitoriamente.",
      "Limpiar burletes y laterales interiores.",
    ],
    auditoria: {
      fecha: "2026-09-23",
      hora: "06:50 hs",
      realizadoPor: "Martín Gómez",
      consumoRegistrado: ["50 ml de Detergente Neutro", "30 ml de Alcohol 70%"],
      observacion: "Burletes limpios y sin restos.",
      fotoNombre: "heladera_2309.jpg",
      fotoUrl: "https://d22fxaf9t8d39k.cloudfront.net/774ec43c6e4f4c9769fd6e31560afbf8e3b1fb5b722d54f393de44ad88d66a1d292325.jpg",
    },
  },
  {
    id: 105,
    nombre: "Desinfección de Cuchillas y Tablas de Corte",
    tipo: "operacional",
    destino: "Sector - Cocina",
    estado: "completada",
    fechaProgramada: "2026-09-23",
    elementosLimpieza: ["1 Cepillo de mano", "Paño estéril"],
    procedimiento: [
      "Inmersión en cuba de sanitizado durante 5 minutos.",
      "Enjuagar y escurrir al aire.",
    ],
    auditoria: {
      fecha: "2026-09-23",
      hora: "14:10 hs",
      realizadoPor: "Martín Gómez",
      consumoRegistrado: ["80 ml de Sanitizante Clorado"],
      observacion: "Cambio de tabla azul solicitado.",
    },
  },
  {
    id: 106,
    nombre: "Lavado profundo de Cámara Frigorífica 2",
    tipo: "pre-operacional",
    destino: "Equipo - Cámara Frigorífica 2",
    estado: "incumplida",
    fechaProgramada: "2026-09-22",
    elementosLimpieza: ["1 Manguera de baja presión", "1 Balde graduado"],
    procedimiento: [
      "Apagar forzadores antes de la aplicación del producto.",
      "Aplicar detergente alcalino espumígeno y enjuagar a fondo.",
    ],
    auditoria: {
      fecha: "2026-09-22",
    },
  },
];